### ISSUE TITLE
Switching {{sketch}} doesn't destroy canvas element, but creates new element

### ISSUE THREAD

**Issue by SciutoAlex** [wxactly/angular-p5#1]
The plugin is great, and it's really helpful. I thought I'd mention that when I switch <p5 sketch='one'></p5> to <p5 sketch='two'></p5>, the plugin freezes the animation (I assume this means, the sketch has been destroyed), but doesn't remove the canvas element.

I found a solution, but I'm no Angular expert, so I thought I'd post it here in case it's useful. I think there must be a better way to do it.

<pre>
.factory('p5WrapperFactory', ['$injector', 'p5', function($injector, p5) {
  var p5Wrapper = {
    node: {},
    init: function(sketch, node) {
      this.destroy();
      this.node = node;
      if(sketch) {
        if($injector.has(sketch)) {
          sketch = $injector.get(sketch);
        }
        this.instance = new p5(sketch, node);
      }
    },
    
    destroy: function() {
      if(this.instance) {
        $(this.node).find('canvas').remove();
        this.instance.remove();
        this.instance = null;
      }
    }
  };
  return function() {
    return Object.create(p5Wrapper);
  };
}]);
</pre>

**Comment by wxactly** [comment]
I know this was working several months ago. Perhaps a newer version of p5.js changed behavior and caused this bug? If you'd like to dig in, the line `this.instance.remove();` called on the `p5` object is supposed to stop the sketch and remove the canvas element. I think ;)

**Comment by SciutoAlex** [comment]
You are right. This is an issue with p5.js. Sorry I forgot to close this.
